name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit and Push README.md
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: 'other: updated README.md'
          add: '.'
          
      # - name: Push new README.md
      #   uses: mikeal/publish-to-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PROFILE_GITHUB_TOKEN }}
      #     BRANCH_NAME: 'main'
